services:
  mailhog:
    platform: linux/amd64 # MailHog não possui imagem ARM oficial
    image: mailhog/mailhog
    ports:
      - "1025:1025" # SMTP (envio)
      - "8025:8025" # Web UI (leitura)

  mailhog-api:
    image: node:20-bookworm
    working_dir: /app
    volumes:
      - ./mailhog-api:/app
    command: sh -c "npm install && npm run dev"
    ports:
      - "8788:8788"
    depends_on:
      - mailhog

  worker-api:
    image: worker-image:latest
    volumes:
      - ./api/package.json:/app/package.json
      - ./api/wrangler.jsonc:/app/wrangler.jsonc
      - ./api/.dev.vars:/app/.dev.vars
      - ./api/tsconfig.json:/app/tsconfig.json
      - ./api/src:/app/src
      - ./cert:/app/cert
    ports:
      - "3333:3333"

  page-site:
    image: page-image:latest
    volumes:
      - ./site/package.json:/app/package.json
      - ./site/next.config.ts:/app/next.config.ts
      - ./site/tsconfig.json:/app/tsconfig.json
      - ./site/.env:/app/.env
      - ./site/public:/app/public
      - ./site/src:/app/src
    ports:
      - "3000:3000"

  page-panel:
    image: page-image:latest
    volumes:
      - ./panel/package.json:/app/package.json
      - ./panel/next.config.ts:/app/next.config.ts
      - ./panel/tsconfig.json:/app/tsconfig.json
      - ./panel/.env:/app/.env
      - ./panel/public:/app/public
      - ./panel/src:/app/src
    ports:
      - "3001:3001"

  page-blog:
    image: page-image:latest
    volumes:
      - ./blog/package.json:/app/package.json
      - ./blog/next.config.ts:/app/next.config.ts
      - ./blog/tsconfig.json:/app/tsconfig.json
      - ./blog/.env:/app/.env
      - ./blog/public:/app/public
      - ./blog/src:/app/src
    ports:
      - "3002:3002"
